<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNAR-5CG9196D0F" failures="6" tests="14" name="com.hackathon.qa.testcases.AppliTest" time="245.553" errors="0" timestamp="29 Nov 2019 04:12:04 GMT" skipped="0">
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="loginuivalidation" time="18.478">
    <failure message="Test &#039;loginuivalidation&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300210222?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'loginuivalidation' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300210222?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateWindow(TestBase.java:125)
at com.hackathon.qa.testcases.AppliTest.loginuivalidation(AppliTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginuivalidation -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="loginuivalidation" time="17.593"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="validloginTest" time="12.024"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="validloginTest" time="11.972"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="invalidUsernameTest" time="14.258">
    <failure message="Test &#039;invalidUsernameTest&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300182185?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'invalidUsernameTest' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300182185?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateElement(TestBase.java:134)
at com.hackathon.qa.Applipages.LoginPage.loginfailed(LoginPage.java:108)
at com.hackathon.qa.testcases.AppliTest.invalidUsernameTest(AppliTest.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidUsernameTest -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="invalidUsernameTest" time="11.520"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="invalidPasswordTest" time="15.506">
    <failure message="Test &#039;invalidPasswordTest&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300167886?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'invalidPasswordTest' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300167886?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateElement(TestBase.java:134)
at com.hackathon.qa.Applipages.LoginPage.loginfailed(LoginPage.java:108)
at com.hackathon.qa.testcases.AppliTest.invalidPasswordTest(AppliTest.java:100)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidPasswordTest -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="invalidPasswordTest" time="11.511"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="canvasValidateTest" time="21.444"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="canvasValidateTest" time="19.536">
    <failure message="Test &#039;Canvas Chart Validation&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300151388?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'Canvas Chart Validation' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300151388?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateWindow(TestBase.java:125)
at com.hackathon.qa.Applipages.HomePage.canvasChartValidation(HomePage.java:73)
at com.hackathon.qa.testcases.AppliTest.canvasValidateTest(AppliTest.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- canvasValidateTest -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="VerifyFlashSaleTest" time="43.585">
    <failure message="Test &#039;VerifyFlashSaleTest&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300106311?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'VerifyFlashSaleTest' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300106311?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateWindow(TestBase.java:125)
at com.hackathon.qa.Applipages.HomePage.verifyFlashSale(HomePage.java:87)
at com.hackathon.qa.testcases.AppliTest.VerifyFlashSaleTest(AppliTest.java:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyFlashSaleTest -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="VerifyFlashSaleTest" time="13.540"/>
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="verifyTransactionTableTest" time="19.198">
    <failure message="Test &#039;verifyTransactionTableTest&#039; of &#039;AppliTools Demo VisualTesting&#039; detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300087128?accountId=VzxHdYJuvEm5iXxQkGTQPA~~" type="com.applitools.eyes.exceptions.DiffsFoundException">
      <![CDATA[com.applitools.eyes.exceptions.DiffsFoundException: Test 'verifyTransactionTableTest' of 'AppliTools Demo VisualTesting' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251827300210364/00000251827300087128?accountId=VzxHdYJuvEm5iXxQkGTQPA~~
at com.applitools.eyes.EyesBase.logSessionResultsAndThrowException(EyesBase.java:524)
at com.applitools.eyes.EyesBase.close(EyesBase.java:497)
at com.applitools.eyes.selenium.SeleniumEyes.close(SeleniumEyes.java:2021)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:509)
at com.applitools.eyes.selenium.Eyes.close(Eyes.java:149)
at com.hackathon.qa.base.TestBase.eyesValidateWindow(TestBase.java:125)
at com.hackathon.qa.testcases.AppliTest.verifyTransactionTableTest(AppliTest.java:133)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyTransactionTableTest -->
  <testcase classname="com.hackathon.qa.testcases.AppliTest" name="verifyTransactionTableTest" time="15.388"/>
</testsuite> <!-- com.hackathon.qa.testcases.AppliTest -->
